### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by jaimerabasco** [jlalvarezfernandez/primer_repositorio#1]
https://github.com/jlalvarezfernandez/primer_repositorio/blob/14174be7df963b653686d4deaff6b861e898552c/Ej02ContarNumerosPositivosNegativosYCeros.java#L53

Creo que deberías poner un comentario en esta linea

**Comment by jlalvarezfernandez** [comment]
Muchas gracias por su apreciación querido colega informático. Lo tendré en cuenta.
Salu2. Jose Luis

**Comment by jaimerabasco** [comment]
De nada, para eso estamos. Pero pon el comentario niño

**Comment by jlalvarezfernandez** [comment]
Ok, ya esta cambiado.
